package entities;
// Generated Apr 23, 2016 9:34:56 PM by Hibernate Tools 4.3.1


import java.util.*;

/**
 * Dskhambenh generated by hbm2java
 */
public class Dskhambenh  implements java.io.Serializable {


     private int stt;
     private Dsbenhnhan dsbenhnhan;
     private String ngayKham;

    public Dskhambenh() {
    }

	
    public Dskhambenh(int stt) {
        this.stt = stt;
    }
    public Dskhambenh(int stt, Dsbenhnhan dsbenhnhan, String ngayKham) {
       this.stt = stt;
       this.dsbenhnhan = dsbenhnhan;
       this.ngayKham = ngayKham;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public Dsbenhnhan getDsbenhnhan() {
        return this.dsbenhnhan;
    }
    
    public void setDsbenhnhan(Dsbenhnhan dsbenhnhan) {
        this.dsbenhnhan = dsbenhnhan;
    }
    public String getNgayKham() {
        return this.ngayKham;
    }
    
    public void setNgayKham(String ngayKham) {
        this.ngayKham = ngayKham;
    }




}


