package entities;
// Generated Apr 23, 2016 9:34:56 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Phieukhambenh generated by hbm2java
 */
public class Phieukhambenh  implements java.io.Serializable {


     private int stt;
     private Dsbenhnhan dsbenhnhan;
     private String trieuChung;
     private Integer loaiBenh;
     private Set thuocs = new HashSet(0);

    public Phieukhambenh() {
    }

	
    public Phieukhambenh(int stt) {
        this.stt = stt;
    }
    public Phieukhambenh(int stt, Dsbenhnhan dsbenhnhan, String trieuChung, Integer loaiBenh, Set thuocs) {
       this.stt = stt;
       this.dsbenhnhan = dsbenhnhan;
       this.trieuChung = trieuChung;
       this.loaiBenh = loaiBenh;
       this.thuocs = thuocs;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public Dsbenhnhan getDsbenhnhan() {
        return this.dsbenhnhan;
    }
    
    public void setDsbenhnhan(Dsbenhnhan dsbenhnhan) {
        this.dsbenhnhan = dsbenhnhan;
    }
    public String getTrieuChung() {
        return this.trieuChung;
    }
    
    public void setTrieuChung(String trieuChung) {
        this.trieuChung = trieuChung;
    }
    public Integer getLoaiBenh() {
        return this.loaiBenh;
    }
    
    public void setLoaiBenh(Integer loaiBenh) {
        this.loaiBenh = loaiBenh;
    }
    public Set getThuocs() {
        return this.thuocs;
    }
    
    public void setThuocs(Set thuocs) {
        this.thuocs = thuocs;
    }




}


