package entities;
// Generated Apr 23, 2016 9:34:56 PM by Hibernate Tools 4.3.1



/**
 * Thuoc generated by hbm2java
 */
public class Thuoc  implements java.io.Serializable {


     private int stt;
     private Phieukhambenh phieukhambenh;
     private Integer loaiThuoc;
     private Integer donVi;
     private Integer soLuong;
     private Integer cachDung;

    public Thuoc() {
    }

	
    public Thuoc(int stt) {
        this.stt = stt;
    }
    public Thuoc(int stt, Phieukhambenh phieukhambenh, Integer loaiThuoc, Integer donVi, Integer soLuong, Integer cachDung) {
       this.stt = stt;
       this.phieukhambenh = phieukhambenh;
       this.loaiThuoc = loaiThuoc;
       this.donVi = donVi;
       this.soLuong = soLuong;
       this.cachDung = cachDung;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public Phieukhambenh getPhieukhambenh() {
        return this.phieukhambenh;
    }
    
    public void setPhieukhambenh(Phieukhambenh phieukhambenh) {
        this.phieukhambenh = phieukhambenh;
    }
    public Integer getLoaiThuoc() {
        return this.loaiThuoc;
    }
    
    public void setLoaiThuoc(Integer loaiThuoc) {
        this.loaiThuoc = loaiThuoc;
    }
    public Integer getDonVi() {
        return this.donVi;
    }
    
    public void setDonVi(Integer donVi) {
        this.donVi = donVi;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }
    public Integer getCachDung() {
        return this.cachDung;
    }
    
    public void setCachDung(Integer cachDung) {
        this.cachDung = cachDung;
    }




}


