/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyphongmach;

import DAO.*;
import entities.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static quanlyphongmach.pnlTraCuuHoSo.bnd;

/**
 *
 * @author Duong Python
 */
public class pnlLapDanhSach extends javax.swing.JPanel {

    /**
     * Creates new form pnlLapDanhSach
     */
    static LapDanhSachDAO  dskDAO= new LapDanhSachDAO();
    public pnlLapDanhSach() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCheck = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnKiemTra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachKham = new javax.swing.JTable();
        btnDangKi = new javax.swing.JButton();
        btnTaoMoi = new javax.swing.JButton();

        jLabel1.setText("Nhập họ tên");

        btnKiemTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check.png"))); // NOI18N
        btnKiemTra.setText("Kiểm tra");
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });

        tblDanhSachKham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachKham.setFocusable(false);
        tblDanhSachKham.getTableHeader().setReorderingAllowed(false);
        tblDanhSachKham.setUpdateSelectionOnSort(false);
        tblDanhSachKham.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tblDanhSachKham);
        if (tblDanhSachKham.getColumnModel().getColumnCount() > 0) {
            tblDanhSachKham.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSachKham.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSachKham.getColumnModel().getColumn(2).setResizable(false);
            tblDanhSachKham.getColumnModel().getColumn(3).setResizable(false);
        }

        btnDangKi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup-icon.png"))); // NOI18N
        btnDangKi.setText("Đăng kí khám");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });

        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-icon.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnDangKi)
                        .addGap(65, 65, 65)
                        .addComponent(btnTaoMoi)
                        .addContainerGap(247, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnKiemTra)
                    .addComponent(btnDangKi)
                    .addComponent(btnTaoMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        // TODO add your handling code here:
        String name = txtCheck.getText();
        Dsbenhnhan bn = pnlTraCuuHoSo.bnd.find(name);
        if (bn == null)
            JOptionPane.showMessageDialog(null, "Chưa có thông tin, cần đăng kí thông tin.");
        else
            JOptionPane.showMessageDialog(null, "Đã có thông tin của bệnh nhân này.");
    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        // TODO add your handling code here:
         frmThem fr = new frmThem();
        fr.setVisible(true);
    }//GEN-LAST:event_btnTaoMoiActionPerformed
    static void LoadData(){
        DefaultTableModel tblModel = new DefaultTableModel();
        tblModel.addColumn("STT");
        tblModel.addColumn("Họ tên");
        tblModel.addColumn("Ngày khám");
        int i = 0;
        for (Dskhambenh dsk: dskDAO.findAll())
        {
            i++;
            tblModel.addRow(new Object[]{i, dsk.getDsbenhnhan().getHoTen(), dsk.getNgayKham()});
        }
        tblDanhSachKham.setModel(tblModel);
        tblDanhSachKham.repaint();
        tblDanhSachKham.revalidate();
        
      

    }
    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:
        frmDangKiKham jfr = new frmDangKiKham();
        jfr.setVisible(true);
    }//GEN-LAST:event_btnDangKiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblDanhSachKham;
    public static javax.swing.JTextField txtCheck;
    // End of variables declaration//GEN-END:variables
}
